name: Test
on:
  pull_request:
    types:
      - opened
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install npm dependencies 📥
        run: npm ci
      - name: Running test cases 🧪
        run: npm test
